name: WorldOfWater
favicon: null
layout_spectrum: 0.3035915514919907
typography_spectrum: 0.8534063340630382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02072d'
    - '#ff0000'
    - '#fcfbf9'
    - '#ff8800'
    - '#fde300'
  brandStrength: 0.7693172483704984
  lightness: 0.7564734236802906
  saturation: 0.375
  rhythmicContrast: 0.6002703551203012
purpose: []
